#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr  9 20:39:56 2022

@author: kelly
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats


eventrootcode_1 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/1.csv")
eventrootcode_2 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/2.csv")
eventrootcode_3 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/3.csv")
eventrootcode_4 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/4.csv")
eventrootcode_5 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/5.csv")
eventrootcode_6 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/6.csv")
eventrootcode_7 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/7.csv")
eventrootcode_8 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/8.csv")
eventrootcode_9 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/9.csv")
eventrootcode_10 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/10.csv")
eventrootcode_11 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/11.csv")
eventrootcode_12 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/12.csv")
eventrootcode_13 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/13.csv")
eventrootcode_14 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/14.csv")
eventrootcode_15 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/15.csv")
eventrootcode_16 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/16.csv")
eventrootcode_17 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/17.csv")
eventrootcode_18 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/18.csv")
eventrootcode_19 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/19.csv")
eventrootcode_20 = pd.read_csv("/Volumes/U_WHU_2T/eventrootcodecsv/20.csv")

DJI = pd.read_csv("/Volumes/U_WHU_2T/indextotal/index/^DJI.csv")
GSPC = pd.read_csv("/Volumes/U_WHU_2T/indextotal/index/^GSPC.csv")
IXIC = pd.read_csv("/Volumes/U_WHU_2T/indextotal/index/^IXIC.csv")

aal = pd.read_csv("/Volumes/U_WHU_2T/indextotal/Airlines/aal.csv")
luv = pd.read_csv("/Volumes/U_WHU_2T/indextotal/Airlines/luv.csv")
ual = pd.read_csv("/Volumes/U_WHU_2T/indextotal/Airlines/ual.csv")

gs = pd.read_csv("/Volumes/U_WHU_2T/indextotal/Banking/gs.csv")
jpm = pd.read_csv("/Volumes/U_WHU_2T/indextotal/Banking/jpm.csv")
ms = pd.read_csv("/Volumes/U_WHU_2T/indextotal/Banking/ms.csv")

abbv = pd.read_csv("/Volumes/U_WHU_2T/indextotal/Healthcare/abbv.csv")
gild = pd.read_csv("/Volumes/U_WHU_2T/indextotal/Healthcare/gild.csv")
pfe = pd.read_csv("/Volumes/U_WHU_2T/indextotal/Healthcare/pfe.csv")

cvx = pd.read_csv("/Volumes/U_WHU_2T/indextotal/Oil & Energy/cvx.csv")
dvn = pd.read_csv("/Volumes/U_WHU_2T/indextotal/Oil & Energy/dvn.csv")
xom = pd.read_csv("/Volumes/U_WHU_2T/indextotal/Oil & Energy/xom.csv")

aapl = pd.read_csv("/Volumes/U_WHU_2T/indextotal/Technology/aapl.csv")
amzn = pd.read_csv("/Volumes/U_WHU_2T/indextotal/Technology/amzn.csv")
msft = pd.read_csv("/Volumes/U_WHU_2T/indextotal/Technology/msft.csv")


r, p = stats.pearsonr(eventrootcode_1.dropna()['AvgTone'], luv.dropna()['Close'])
print(f"Scipy computed Pearson1 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_2.dropna()['AvgTone'], luv.dropna()['Close'])
print(f"Scipy computed Pearson2 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_3.dropna()['AvgTone'], luv.dropna()['Close'])
print(f"Scipy computed Pearson3 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_4.dropna()['AvgTone'], luv.dropna()['Close'])
print(f"Scipy computed Pearson4 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_5.dropna()['AvgTone'],luv.dropna()['Close'])
print(f"Scipy computed Pearson5 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_6.dropna()['AvgTone'], luv.dropna()['Close'])
print(f"Scipy computed Pearson6 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_7.dropna()['AvgTone'], luv.dropna()['Close'])
print(f"Scipy computed Pearson7 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_8.dropna()['AvgTone'], luv.dropna()['Close'])
print(f"Scipy computed Pearson8 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_9.dropna()['AvgTone'],luv.dropna()['Close'])
print(f"Scipy computed Pearson9 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_10.dropna()['AvgTone'], luv.dropna()['Close'])
print(f"Scipy computed Pearson10 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_11.dropna()['AvgTone'],luv.dropna()['Close'])
print(f"Scipy computed Pearson11 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_12.dropna()['AvgTone'],luv.dropna()['Close'])
print(f"Scipy computed Pearson12 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_13.dropna()['AvgTone'],luv.dropna()['Close'])
print(f"Scipy computed Pearson13 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_14.dropna()['AvgTone'], luv.dropna()['Close'])
print(f"Scipy computed Pearson14 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_15.dropna()['AvgTone'], luv.dropna()['Close'])
print(f"Scipy computed Pearson15 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_16.dropna()['AvgTone'],luv.dropna()['Close'])
print(f"Scipy computed Pearson16 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_17.dropna()['AvgTone'],luv.dropna()['Close'])
print(f"Scipy computed Pearson17 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_18.dropna()['AvgTone'],luv.dropna()['Close'])
print(f"Scipy computed Pearson18 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_19.dropna()['AvgTone'],luv.dropna()['Close'])
print(f"Scipy computed Pearson19 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_20.dropna()['AvgTone'],luv.dropna()['Close'])
print(f"Scipy computed Pearson20 r: {r} and p-value: {p}")

r, p = stats.pearsonr(eventrootcode_1.dropna()['NumMentions'], luv.dropna()['Close'])
print(f"Scipy computed Pearson1 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_2.dropna()['NumMentions'],luv.dropna()['Close'])
print(f"Scipy computed Pearson2 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_3.dropna()['NumMentions'], luv.dropna()['Close'])
print(f"Scipy computed Pearson3 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_4.dropna()['NumMentions'],luv.dropna()['Close'])
print(f"Scipy computed Pearson4 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_5.dropna()['NumMentions'], luv.dropna()['Close'])
print(f"Scipy computed Pearson5 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_6.dropna()['NumMentions'],luv.dropna()['Close'])
print(f"Scipy computed Pearson6 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_7.dropna()['NumMentions'], luv.dropna()['Close'])
print(f"Scipy computed Pearson7 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_8.dropna()['NumMentions'], luv.dropna()['Close'])
print(f"Scipy computed Pearson8 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_9.dropna()['NumMentions'],luv.dropna()['Close'])
print(f"Scipy computed Pearson9 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_10.dropna()['NumMentions'],luv.dropna()['Close'])
print(f"Scipy computed Pearson10 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_11.dropna()['NumMentions'], luv.dropna()['Close'])
print(f"Scipy computed Pearson11 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_12.dropna()['NumMentions'],luv.dropna()['Close'])
print(f"Scipy computed Pearson12 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_13.dropna()['NumMentions'], luv.dropna()['Close'])
print(f"Scipy computed Pearson13 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_14.dropna()['NumMentions'], luv.dropna()['Close'])
print(f"Scipy computed Pearson14 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_15.dropna()['NumMentions'], luv.dropna()['Close'])
print(f"Scipy computed Pearson15 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_16.dropna()['NumMentions'],luv.dropna()['Close'])
print(f"Scipy computed Pearson16 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_17.dropna()['NumMentions'], luv.dropna()['Close'])
print(f"Scipy computed Pearson17 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_18.dropna()['NumMentions'], luv.dropna()['Close'])
print(f"Scipy computed Pearson18 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_19.dropna()['NumMentions'],luv.dropna()['Close'])
print(f"Scipy computed Pearson19 r: {r} and p-value: {p}")
r, p = stats.pearsonr(eventrootcode_20.dropna()['NumMentions'], luv.dropna()['Close'])
print(f"Scipy computed Pearson20 r: {r} and p-value: {p}")



